- name: install the all packages
  hosts: all
  become: yes
  vars_files:
  - credentials.yaml
  tasks:
  - name: install the postfix
    ansible.builtin.dnf:
      name: postfix
      state: latest

  - name: install the gcc
    ansible.builtin.dnf:
      name: gcc
      state: latest

  
